# Generated by Django 4.2.1 on 2023-06-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_labtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='test_name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='price',
            new_name='test_price',
        ),
    ]
