# Generated by Django 4.2.1 on 2023-06-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_name_patient_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test_price',
            new_name='price',
        ),
    ]
