# Generated by Django 4.2.1 on 2023-06-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_patient_name_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
